### ISSUE TITLE
Request for rendering panoramic images command

### ISSUE THREAD

**Issue by iamblitzcrank** [LetianHuang/op43dgs#1]
Thanks for your awesome works and code release!
Could you please upload the command line for rendering panoramic images?

I also have a question about "diff-gaussian-rasterization-panorama".
Is it also implemented for using bacward.cu to train multi-view panorama images?

Have a nice day.

**Comment by LetianHuang** [comment]
I'm glad that you are interested in this repo.

1. The command for rendering a panoramic image is the same as for rendering a pinhole image. 
2. Yes, the current release of "diff-gaussian-rasterization-panorama" includes codes for gradient backpropagation, which, as shown on the project homepage, can be used for training with multi-view panoramic images.

Have a nice day too!

**Comment by gs14iitbbs** [comment]
> I'm glad that you are interested in this repo.
> 
>     1. The command for rendering a panoramic image is the same as for rendering a pinhole image.
> 
>     2. Yes, the current release of "diff-gaussian-rasterization-panorama" includes codes for gradient backpropagation, which, as shown on the project homepage, can be used for training with multi-view panoramic images.
> 
> 
> Have a nice day too!

How to get the initial poses for training with multi-view panoramic images ? Colmap is not able to work.

**Comment by LetianHuang** [comment]
For pose acquisition, the panoramic demo on our project page https://letianhuang.github.io/op43dgs/ uses the Matterport3D dataset, which includes camera poses corresponding to the panoramic images rather than relying on algorithmic estimation. Since our work focuses on minimizing errors in the projection of 3D-GS and provides more generalized projections across camera models, we do not specifically address pose estimation for non-pinhole camera models.

Thank you for your interest in our work!

**Comment by yuancaimaiyi** [comment]
@LetianHuang 
Excuse me, I looked at the code and didn't find the panorama data and panorama pose load part of the code. I would like to ask how to input the panorama and corresponding pose in train.py . In addition, you mentioned your panorama image and pose come from Matterport3D, can you provide test data? Thank you so much!

**Comment by LeoDarcy** [comment]
> @LetianHuang Excuse me, I looked at the code and didn't find the panorama data and panorama pose load part of the code. I would like to ask how to input the panorama and corresponding pose in train.py . In addition, you mentioned your panorama image and pose come from Matterport3D, can you provide test data? Thank you so much!

Our test data can be obtained following this [instruction](https://github.com/LeoDarcy/360GS/tree/main/DataPreparation).
