### ISSUE TITLE
Use pinhole to train?

### ISSUE THREAD

**Issue by haofengsiji** [LetianHuang/op43dgs#5]
Is the process using a pinhole to train, and then the image can be rendered as a pinhole, fisheye ..., like this?

**Comment by LetianHuang** [comment]
Yes, after training with the pinhole model, the scene can be adapted to different camera models by replacing the submodules of ```diff-gaussian-rasterization-(pinhole,panorama, ...)```, enabling the rendering of pinhole, fisheye, panorama, and other types of images. If the backward propagation code ```backward.cu``` for the corresponding camera model has been implemented, it is also possible to use pinhole, panorama, fisheye, and other models' images as inputs to train the scene, since the optimal projection proposed in our paper is differentiable.

**Comment by scott198510** [comment]
> Yes, after training with the pinhole model, the scene can be adapted to different camera models by replacing the submodules of `diff-gaussian-rasterization-(pinhole,panorama, ...)`, enabling the rendering of pinhole, fisheye, panorama, and other types of images. If the backward propagation code `backward.cu` for the corresponding camera model has been implemented, it is also possible to use pinhole, panorama, fisheye, and other models' images as inputs to train the scene, since the optimal projection proposed in our paper is differentiable.

As you said, is the rendering result  of fisheye images in your paper obtained by directly training fisheye images or by rendering non fisheye images after training?

**Comment by LetianHuang** [comment]
In theory, it's all feasible. However, in the paper, this is done primarily to demonstrate that our projection strategy can adapt to other complex camera models. Thus, the novel views are rendered using our projection method after training under a pinhole camera model.

**Comment by LetianHuang** [comment]
In theory, it's both feasible. However, in the paper, this is done primarily to demonstrate that our projection strategy can adapt to other complex camera models. Thus, the novel views are rendered using our projection method after training under a pinhole camera model.

**Comment by scott198510** [comment]
> In theory, it's both feasible. However, in the paper, this is done primarily to demonstrate that our projection strategy can adapt to other complex camera models. Thus, the novel views are rendered using our projection method after training under a pinhole camera model.

Thanks for your reply.

Another question is, the original fisheye image has black borders on all four corners. As you mentioned, you used a undistorted fisheye image without black borders. After participating in training and rendering, how did the black borders appear in the rendering result? Is it adding distortion? Also, the Matterport3D dataset does not have fisheye data, it is a panoramic dataset. How did you obtain it?
