### ISSUE TITLE
readPanoramaInfo and readFisheyeInfo was empty

### ISSUE THREAD

**Issue by LaFeuilleMorte** [LetianHuang/op43dgs#8]
Hi, It seemed that your preprocess script for panorama and fisheye cameras are missing. How can I preprocess panorama datasets and fisheye datasets?

**Comment by LetianHuang** [comment]
Hello, we're thrilled that you find our work interesting. To process other datasets, you can write custom scripts tailored to your requirements. Our main focus is on conducting a detailed error analysis of Gaussian projections and providing a differentiable rendering algorithm with minimal projection error that supports various camera models. : )

**Comment by LetianHuang** [comment]
Hello, we're thrilled that you find our work interesting. To process other datasets, you can write custom scripts tailored to your requirements. Our main focus is on conducting a detailed error analysis of Gaussian projections and providing a differentiable rendering algorithm with minimal projection error that supports various camera models. : )

**Comment by LetianHuang** [comment]
As for training with panoramic images, you can refer to our other work on reconstructing indoor scenes from panoramic images for guidance on processing the [Matterport dataset](https://niessner.github.io/Matterport/). The dataset reader implementation is available here: https://github.com/LeoDarcy/360GS/blob/LetianHuang-layout-reg/scene/dataset_readers.py.  However, this work is not fully open-sourced yet. We plan to gradually release additional components in the future. : )

**Comment by LaFeuilleMorte** [comment]
> As for training with panoramic images, you can refer to our other work on reconstructing indoor scenes from panoramic images for guidance on processing the [Matterport dataset](https://niessner.github.io/Matterport/). The dataset reader implementation is available here: https://github.com/LeoDarcy/360GS/blob/LetianHuang-layout-reg/scene/dataset_readers.py. However, this work is not fully open-sourced yet. We plan to gradually release additional components in the future. : )

It appeared that the FOVX, FOVY was using a fixed numbers (FovY = focal2fov(w * 0.2, h) 
FovX = focal2fov(w * 0.2, w) )? 
Is there any mathematical equations for explaining this?
 From my knowledge, the intrinsics does not matter in panorama images. So I simply  set FOVX = 2* pi ;   FOVY= pi, is that right for pano images? My images are 1024 * 512 using equirectangular projection.

**Comment by LetianHuang** [comment]
I suggest you carefully review the supplementary materials of the paper and the ```diff-gaussian-rasterization-panorama``` source code in the repository. The FoV parameter does not affect the results of panoramic images.  
In addition, the source code you mentioned includes the comment ```# Use any number instead of Fov```, indicating that any value can be used.
