### ISSUE TITLE
Question about the invertible matrix Q in equation 18

### ISSUE THREAD

**Issue by JIANG-CX** [LetianHuang/op43dgs#9]
Great work !
I am curious about the meaning of the invertible matrix Q and how this matrix is obtained. Thanks.
![image](https://github.com/user-attachments/assets/8f2ed41c-eec9-413a-af3a-66879860c283)

**Comment by LetianHuang** [comment]
Thank you very much for recognizing this work!

 First, it is important to note that the optimal projection plane is not parallel to the coordinate axes. As a result, the Gaussian projected onto this plane requires three parameters to be described in the original coordinate system. However, a Gaussian on a plane inherently has only two axes, and the rank of its covariance matrix is 2. To represent it using only two parameters, we establish a local coordinate system with the projection center as the origin. The transformation matrix between these two coordinate systems is the Q matrix, which is essentially a rotation matrix.

If you have any further questions, feel free to ask!

**Comment by JIANG-CX** [comment]
Thank you for your response. When establishing a local coordinate system, there are multiple options because the plane can rotate around the vector from the camera to the Gaussian. I am curious about how you select Q as the specific local coordinate system. If we choose a different Q, will the results vary? Thank you.
________________________________
发件人: LetianHuang ***@***.***>
发送时间: 2024年12月10日 22:31
收件人: LetianHuang/op43dgs ***@***.***>
抄送: JIANG Chenxing ***@***.***>; Author ***@***.***>
主题: Re: [LetianHuang/op43dgs] Question about the invertible matrix Q in equation 18 (Issue #9)


Thank you very much for recognizing this work!

First, it is important to note that the optimal projection plane is not parallel to the coordinate axes. As a result, the Gaussian projected onto this plane requires three parameters to be described in the original coordinate system. However, a Gaussian on a plane inherently has only two axes, and the rank of its covariance matrix is 2. To represent it using only two parameters, we establish a local coordinate system with the projection center as the origin. The transformation matrix between these two coordinate systems is the Q matrix, which is essentially a rotation matrix.

If you have any further questions, feel free to ask!

―

**Comment by LetianHuang** [comment]
In theory, any local coordinate system can be used without affecting the projection error. However, only when two mutually orthogonal vectors within the optimal projection plane are chosen as the local coordinate system can the projection plane Gaussian be represented using two parameters instead of three.

**Comment by JIANG-CX** [comment]
I see. Thanks for your reply. 😊
